services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Microsoft.AspNetCore=Information
    volumes:
      # Mount storage for development
      - ./API/storage:/app/storage
