services:
  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: assignment_grading_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "14330:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - prn_network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # API Application
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: assignment_grading_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Default=Server=sqlserver;Database=Swd392;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;MultipleActiveResultSets=true
      - Storage__Root=storage
      - Storage__SevenZipPath=/usr/bin/7z
    ports:
      - "5000:8080"
    volumes:
      - ./API/storage:/app/storage
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - prn_network
    restart: unless-stopped

networks:
  prn_network:
    name: assignment_grading_network
    driver: bridge

volumes:
  sqlserver_data:
    name: assignment_grading_data
